### ISSUE TITLE
How do you debug?

### ISSUE THREAD

**Issue by TamaHobbit** [thindil/vim-ada#1]
I was wondering how you debug your code, as I didn't see any plugin in your list for interacting with gdb. I just got VeBugger working, which works excellently even on windows. Perhaps you should give that a try if you don't have a debugger yet.

**Comment by thindil** [comment]
Main reason why here are no any debugger related plugin is that I have very bad luck to find any good integration debugger <-> Vim. I will look at this plugin, but for now I see one problem: it dependency is more than just VimL. I'm trying to keep this package set clean from other dependencies than external programs, but maybe now it is time to change this rule :)
And back to question: I often use or heavy scripted gdb or good, old DDD (for gdb and many other debbugers) :)

**Comment by thindil** [comment]
My proposition for now - maybe instead of adding it, add to README.md section "Recommended plugins" and list VeBugger there? At this moment I'm doing major changes to the project (like switching from tags to LSP) thus probably many thing will be changed or removed. And they can be added to "Recommended plugins" section too.

**Comment by thindil** [comment]
Ok, I added list of recommended plugins to the wiki: https://github.com/thindil/vim-ada/wiki/Recommended-plugins 
Feel free to add something there if you think it should be added :)
I'm closing for now this issue, thank you for your proposition. If you want add something here, just reopen it.
